### ISSUE TITLE
Add pagination (limit/offset) support on stored views

### ISSUE THREAD

**Issue by jaw111** [dydra/support#24]
Would be great to be able to set the offset and limit for a query by adding these to the query part of the view URI e.g. `http://dydra.com/jhacker/foaf/all.srj?limit=5&offset=5`.

In the HTML view you could also add buttons to paginate to next/previous/first page and drop-down to select number of results per page.

**Comment by tpluscode** [comment]
I would go even farther as to allow parametrizing views with query parameters. Such that possibilities would not be limited to `limit`/`offset` :wink:

`http://dydra.com/jhacker/foaf/all.srj?limit=5&offset=5&prop=dcterms:title`

```
select * 
where
{
   ?thing @prop ?title .
}
limit @limit
offset @offset
```

**Comment by lisp** [comment]
dydra's sparql http api implements the [sparql 1.1 protocol](https://www.w3.org/TR/sparql11-protocol/).
in order to support views and facilitate cached query implementations, it adopts elements from the [HTTP communication protocol for Sesame 2](http://rdf4j.org/sesame/2.7/docs/system.docbook?view#repository-queries) to permit variable bindings.
n order to facilitate programmatic and federated access to stored views, the api also [extends](https://github.com/dydra/http-api-tests/tree/master/extensions/sparql-protocol/values) the sparql standard further, with support for [values clauses](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#inline-data) as request arguments.

these mechanism all involve introducing variable bindings into the dynamic query evaluation context.
arbitrary interpolated language elements, on the other hand are not supported, as we do not perform text interpolation, but rather establish syntax-constrained variable bindings.

that means that limit and offset cannot be specified as if they were arbitrary query parameters.
they are supported, but are treated as special constraints on the data-flow in the query processor and override any slice specified by the query text itself.

**Comment by jaw111** [comment]
> they are supported, but are treated as special constraints on the data-flow in the query processor and override any slice specified by the query text itself.

is there any documentation/examples about how to make such a request?
