### ISSUE TITLE
Repository is giving 504 timeout

### ISSUE THREAD

**Issue by jaw111** [dydra/support#50]
i cannot access this repository:

http://dydra.com/nlv01111/dbeerpedia

keep getting a 504 response:

504 Gateway Time-out
nginx/1.4.6 (Ubuntu)

**Comment by lisp** [comment]
the repository was subject to numerous operations over the hours following its creation at about T13:33:23Z. of these, there were numerous failed queries, one of which involved a write transaction.
due to unclear circumstances, this query left an unattended write lock, which prevented the web ui from refreshing the respective admin page.
we are looking into that constraint, as it is unexpected.
in the meantime, the lock has been released and the repository admin page should again be available.
