### ISSUE TITLE
Queries giving 504 response on nlv01111/dbeerpedia repo

### ISSUE THREAD

**Issue by jaw111** [dydra/support#51]
The default query is giving a 504 via the GUI:

http://dydra.com/nlv01111/dbeerpedia/@query

Also tried querying the sparql endpoint directly, also gives 504:

```
curl http://dydra.com/nlv01111/dbeerpedia/sparql
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by lisp** [comment]
I cannot see logs from here. yesterday, the failures were precipitated by
invalid requests. Will look in a bit.

Am 10.09.2017 16:22 schrieb "John Walker" <notifications@github.com>:

**Comment by lisp** [comment]
this issue is associated with a course of (undisclosed) events.
it would appear that, immediately prior to the _long_ string of failures, a repository of this name was deleted and a second repository was renamed to take its place.
it appears that this combination led several processes which had cached information about the original to become confused, in that it still existed, but its revision history did not agree with that of the original.
we will investigate, how to avoid this in the future.
